# Generated by Django 5.2.1 on 2025-05-31 21:59

import django.db.models.deletion
import myst_api.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='myst_api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=myst_api.models.order.generate_order_id, editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
