# Generated by Django 5.2.1 on 2025-05-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0002_address_order_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='cad', max_length=3),
            preserve_default=False,
        ),
    ]
