# Generated by Django 5.2.1 on 2025-05-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0002_productimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'order')},
        ),
    ]
