# Generated by Django 5.2.1 on 2025-05-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0003_alter_productimage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_street_address', models.CharField(max_length=255)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_prov_state', models.CharField(max_length=100)),
                ('customer_postal_zip_code', models.CharField(max_length=20)),
                ('customer_address_type', models.CharField(choices=[('Residential', 'RESIDENTIAL'), ('Commercial', 'COMMERCIAL')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='myst_api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='myst_api.customer'),
        ),
    ]
