# Generated by Django 5.2.1 on 2025-05-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0003_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='ca', max_length=100),
            preserve_default=False,
        ),
    ]
