# Generated by Django 5.2.1 on 2025-05-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0004_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, choices=[('canada_post', 'CANADA_POST'), ('ups', 'UPS'), ('fedex', 'FEDEX'), ('dhl', 'DHL'), ('purolator', 'PUROLATOR')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processing', 'PROCESSING'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELED')], max_length=50),
        ),
    ]
