# Generated by Django 5.2.1 on 2025-06-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='allowed_on_page',
            field=models.BooleanField(default=False),
        ),
    ]
