# Generated by Django 5.2.1 on 2025-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0007_review_allowed_on_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(default='izaakford30@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
