# Generated by Django 5.2.1 on 2025-06-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_api', '0008_review_reviewer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
