version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./myst_backend
    container_name: myst_backend
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "7999:7999"
    depends_on:
      - mysql

frontend:
  build: ./myst_frontend
  container_name: myst_frontend
  restart: "no"
  volumes:
    - myst_frontend_dist:/app/dist
  environment:
    VITE_API_URL: ${VITE_API_URL}
    VITE_ASSETS_URL: ${VITE_ASSETS_URL}
    VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
  command: >
    sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    container_name: myst_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/static
      - media_data:/app/media
      - myst_frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
  static_data:
  media_data:
  myst_frontend_dist:
