version: "3.8"

services:
  myst_db:
    image: mysql:9.3.0
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - myst_mysql_data:/var/lib/mysql
    networks:
      - myst_network
      - nginx-proxy_npm-network

  myst_backend:
    image: iforddow/myst_backend:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    depends_on:
      - myst_db
    networks:
      - myst_network
      - nginx-proxy_npm-network

  myst_frontend:
    image: iforddow/myst_frontend:latest
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_ASSETS_URL: ${VITE_ASSETS_URL}
      VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
    networks:
      - myst_network
      - nginx-proxy_npm-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  myst_network:
    driver: overlay
    ipam:
      config:
        - subnet: 10.10.20.0/24
  nginx-proxy_npm-network:
    external: true

volumes:
  myst_mysql_data:
  static_data:
  media_data:
  myst_frontend_dist:
