version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${project.MYSQL_DATABASE}
      MYSQL_USER: ${project.MYSQL_USER}
      MYSQL_PASSWORD: ${project.MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${project.MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./myst_backend
    container_name: myst_backend
    restart: always
    environment:
      MYSQL_DATABASE: ${project.MYSQL_DATABASE}
      MYSQL_USER: ${project.MYSQL_USER}
      MYSQL_PASSWORD: ${project.MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${project.MYSQL_ROOT_PASSWORD}
      CORS_ALLOW_ORIGINS: ${project.CORS_ALLOW_ORIGINS}
      STRIPE_WEBHOOK_SECRET: ${project.STRIPE_WEBHOOK_SECRET}
      STRIPE_SECRET_KEY: ${project.STRIPE_SECRET_KEY}
      EMAIL_BACKEND: ${project.EMAIL_BACKEND}
      EMAIL_HOST: ${project.EMAIL_HOST}
      EMAIL_PORT: ${project.EMAIL_PORT}
      EMAIL_USE_TLS: ${project.EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${project.EMAIL_USE_SSL}
      EMAIL_HOST_USER: ${project.EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${project.EMAIL_HOST_PASSWORD}
      SECRET_KEY: ${project.SECRET_KEY}
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - mysql

frontend:
  build: ./myst_frontend
  container_name: myst_frontend
  restart: "no"
  volumes:
    - myst_frontend_dist:/app/dist
  environment:
    VITE_API_URL: ${project.VITE_API_URL}
    VITE_ASSETS_URL: ${project.VITE_ASSETS_URL}
    VITE_STRIPE_PUBLISHABLE_KEY: ${project.VITE_STRIPE_PUBLISHABLE_KEY}
  command: >
    sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    container_name: myst_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/static
      - media_data:/app/media
      - myst_frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
  static_data:
  media_data:
  myst_frontend_dist:
