# Generated by Django 5.2.1 on 2025-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_commerce', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/product_images/'),
        ),
    ]
