# Generated by Django 5.2.1 on 2025-05-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myst_commerce', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('canceled', 'CANCELED')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Completed', 'COMPLETED'), ('Failed', 'FAILED'), ('Refunded', 'REFUNDED'), ('Disputed', 'DISPUTED')], max_length=50)),
            ],
        ),
    ]
